### ISSUE TITLE
Import this project in Android Studio

### ISSUE THREAD

**Issue by dhaval-khant** [halogenOS/android_packages_inputmethods_LatinIME#1]
I want to import this project  in Android Studio.
Can you please give me steps for same?
Thanks in advanced.

**Comment by msfjarvis** [comment]
Clone, then import in Android studio, it will automatically gradle-ify it.

**Comment by xdevs23** [comment]
Or use my `usefulscriptsxd` to generate a gradle project out of it. You can find guides about how to use linux around the internet.

**Comment by dhaval-khant** [comment]
There are many scripts are available in your repository which script i need to use to generate Gradle project.Thanks for your response.

**Comment by regalstreak** [comment]
Look on @xdevs23's github

**Comment by xdevs23** [comment]
@dhaval-khant Self-explanatory: `makegradleproject.sh`, https://github.com/xdevs23/usefulscriptsxd/blob/master/scripts/makegradleproject.sh

**Comment by dhaval-khant** [comment]
Getting below message while using above script.

Not a compatible project. Please make sure that you have a src folder

**Comment by xdevs23** [comment]
Yeah, you need to cd to the correct directory first like `packages/inputmethods/LatinIME/java` :neutral_face:

**Comment by msfjarvis** [comment]
Stop this already please, I'm seeing no point.
